services:
  mysql:
    image: mysql:8.0
    container_name: video-service-mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/video-service.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=video-service
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=admin
      - MYSQL_RANDOM_ROOT_PASSWORD=admin
    networks:
      - video_service_network
  redis:
    image: redis:7.2.5
    container_name: video-service-redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis-config:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - video_service_network
  mongodb:
    image: mongo:6.0.16
    container_name: video-service-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
      - MONGO_INITDB_DATABASE=video-service
    networks:
      - video_service_network
  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft 필수 설정
      KAFKA_NODE_ID: 1  # 브로커 노드 ID
      CLUSTER_ID: 'EpwKlK0lR6qKZW0cGwZz8w'  # 클러스터 고유 식별자

      # 리스너 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'

      # KRaft 모드 설정
      KAFKA_PROCESS_ROLES: 'broker,controller'  # 브로커와 컨트롤러 역할 통합
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'  # 컨트롤러 쿼럼 설정
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'  # 컨트롤러 통신용 리스너

      # 복제 관련 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - video_service_network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:9090"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - video_service_network    # 네트워크 추가
    depends_on:
      - kafka

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../video-apps/app-batch/:/var/jenkins_home/workspace/app-batch
    environment:
      - TZ=Asia/Seoul
    networks:
      - video_service_network

networks:
  video_service_network:
    driver: bridge