spring.application.name: video-service
spring.profiles.active: local

spring:
  config:
    import:
      - adapters.yaml
      - monitoring.yml
      - logging.yml
  web.resources.add-mappings: false